name: Deploy to EC2

on:
  workflow_dispatch:  # allows manual triggers via GitHub API or UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-strict: false
      - name: Deploy to EC2 Test Environment
        run: |
          # Write private key from secret
          echo "${{ secrets.PALMTREE_ETL_EC2_SSH_KEY_TEST }}" > key.pem
          chmod 600 key.pem

          # Use temporary known_hosts file
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@35.178.99.172 "
            cd /var/www/palmtree_etl &&
            git pull &&
            sudo systemctl restart palmtree_etl
          "

          # Cleanup
          rm -f key.pem
          