name: Deploy to EC2

on:
  workflow_dispatch:  # allows manual triggers via GitHub API or UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 Test Environment
        run: |
          echo "${{ secrets.PALMTREE_ETL_EC2_SSH_KEY_TEST }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ubuntu@35.178.99.172 "
            cd /var/www/palmtree_etl &&
            git pull &&
            systemctl restart palmtree_etl
          "
